enabled: true
copyright: 'Copyright &copy; Aaron Meeuwsen 2019-2020'
favicon: favicon.png
error_header_image: home-bg.jpg
social_icons:
  -
    icon: fa-twitter
    url: 'https://www.twitter.com/'
  -
    icon: fa-facebook
    url: 'https://www.facebook.com/'
  -
    icon: fa-github
    url: 'https://www.github.com/'
default_header_image: header-banner.jpg
